import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader, CardTitle, } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { spendingLimit } from "@/data/seed";
import { ShieldCheckIcon } from "lucide-react";
export function SpendingLimit() {
    const percentUsed = Math.round((spendingLimit.spent / spendingLimit.budget) * 100);
    return (_jsxs(Card, { children: [_jsxs(CardHeader, { className: "flex flex-row items-center justify-between space-y-0 pb-2", children: [_jsx(CardTitle, { className: "text-base font-semibold", children: "Monthly Spending Limit" }), _jsx("div", { className: "flex size-8 items-center justify-center rounded-lg bg-muted", children: _jsx(ShieldCheckIcon, { className: "size-4 text-muted-foreground" }) })] }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-muted-foreground", children: "Budget" }), _jsxs("p", { className: "text-2xl font-bold tabular-nums tracking-tight", children: ["$", spendingLimit.budget.toLocaleString(), " ", _jsx("span", { className: "text-sm font-normal text-muted-foreground", children: spendingLimit.currency })] })] }), _jsx(Progress, { value: percentUsed, className: "h-2" }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-muted-foreground", children: "Spend" }), _jsxs("p", { className: "font-semibold tabular-nums", children: ["$", spendingLimit.spent.toLocaleString()] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-xs text-muted-foreground", children: "Remaining" }), _jsxs("p", { className: "font-semibold tabular-nums text-emerald-600 dark:text-emerald-400", children: ["$", spendingLimit.remaining.toLocaleString()] })] })] }), _jsxs("p", { className: "text-xs text-muted-foreground", children: [spendingLimit.periodStart, " - ", spendingLimit.periodEnd] })] })] }));
}
