"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "motion/react";
import { SnowflakeIcon, WifiIcon } from "lucide-react";
import { cn } from "@/lib/utils";
export function InteractiveCard({ card, frozen, }) {
    const [flipped, setFlipped] = useState(false);
    const [cvvRevealed, setCvvRevealed] = useState(false);
    return (_jsx("div", { className: "aspect-[1.586/1] w-full cursor-pointer sm:max-w-[400px]", style: { perspective: "1000px" }, onClick: () => setFlipped((f) => !f), children: _jsxs(motion.div, { className: "relative h-full w-full", style: { transformStyle: "preserve-3d" }, animate: { rotateY: flipped ? 180 : 0 }, transition: { type: "spring", stiffness: 300, damping: 30 }, children: [_jsxs("div", { className: cn("absolute inset-0 flex flex-col justify-between rounded-2xl p-5", card.color), style: { backfaceVisibility: "hidden" }, children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsx("span", { className: "text-sm font-medium", children: card.name }), _jsx(Image, { src: card.network === "visa" ? "/logos/visa-com.svg" : "/logos/mastercard-com.svg", alt: card.network, width: 48, height: 32, className: "h-8 w-auto object-contain" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "h-8 w-11 rounded-md bg-gradient-to-br from-amber-300 to-amber-500 opacity-80" }), _jsx(WifiIcon, { className: "size-5 rotate-90 opacity-60" })] }), _jsxs("p", { className: "font-mono text-base tracking-widest tabular-nums", children: ["**** **** **** ", card.last4] }), _jsxs("div", { className: "flex items-end justify-between", children: [_jsx("span", { className: "text-xs font-medium uppercase tracking-wide", children: card.holder }), _jsx("span", { className: "text-xs tabular-nums", children: card.expiry })] })] }), _jsxs("div", { className: "absolute inset-0 flex flex-col rounded-2xl bg-primary text-primary-foreground", style: {
                        backfaceVisibility: "hidden",
                        transform: "rotateY(180deg)",
                    }, children: [_jsx("div", { className: "mt-6 h-10 w-full bg-foreground/80" }), _jsxs("div", { className: "flex flex-1 flex-col justify-between p-5 pt-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "h-8 flex-1 rounded bg-muted/20" }), _jsx("div", { className: "flex h-8 w-14 items-center justify-center rounded bg-white", onClick: (e) => {
                                                e.stopPropagation();
                                                setCvvRevealed((r) => !r);
                                            }, children: _jsx(AnimatePresence, { mode: "wait", children: cvvRevealed ? (_jsx(motion.span, { initial: { scale: 0.5, opacity: 0 }, animate: { scale: 1, opacity: 1 }, exit: { scale: 0.5, opacity: 0 }, className: "font-mono text-sm font-bold text-foreground tabular-nums", children: card.cvv }, "cvv")) : (_jsx(motion.span, { initial: { scale: 0.5, opacity: 0 }, animate: { scale: 1, opacity: 1 }, exit: { scale: 0.5, opacity: 0 }, className: "font-mono text-sm text-muted-foreground", children: "***" }, "hidden")) }) })] }), _jsx("p", { className: "text-xs text-primary-foreground/60", children: "Tap CVV box to reveal. Click card to flip back." })] })] }), _jsx(AnimatePresence, { children: frozen && (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, className: "absolute inset-0 z-50 flex flex-col items-center justify-center gap-2 rounded-2xl bg-background/70 backdrop-blur-sm", children: [_jsx(SnowflakeIcon, { className: "size-8 text-muted-foreground" }), _jsx("span", { className: "text-sm font-medium text-muted-foreground", children: "Card Frozen" })] })) })] }) }));
}
